server:
  port: 9000

spring:
  application:
    name: auth-server

  datasource:
    url: jdbc:mysql://localhost:3306/${db}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USER}
    password: ${PW}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_KEY}
  expiration: 3600

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
