server:
  port: 9000

spring:
  application:
    name: auth-server

  datasource:
    url: jdbc:mysql://localhost:3306/auth_login
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: my-very-secret-key-that-is-long-enough
  expiration: 3600

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
